# Generated by Django 6.0.1 on 2026-05-10 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CareerOpening",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("role", models.CharField(max_length=140)),
                ("location", models.CharField(max_length=120)),
                ("employment_type", models.CharField(max_length=80)),
            ],
            options={
                "ordering": ("sort_order", "id"),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DonationAmount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("amount", models.CharField(max_length=40)),
                ("label", models.CharField(max_length=120)),
                ("select_value", models.CharField(max_length=40)),
            ],
            options={
                "ordering": ("sort_order", "id"),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FeatureCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("section_key", models.SlugField(default="home_features")),
                ("icon", models.CharField(blank=True, max_length=12)),
                ("title", models.CharField(max_length=160)),
                ("body", models.TextField()),
            ],
            options={
                "ordering": ("sort_order", "id"),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FocusArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("image", models.FileField(blank=True, upload_to="cms/")),
                (
                    "static_image",
                    models.CharField(
                        blank=True,
                        help_text="Optional static image path, for example images/im-01.jpeg.",
                        max_length=255,
                    ),
                ),
                ("image_alt", models.CharField(blank=True, max_length=255)),
                ("slug", models.SlugField(unique=True)),
                ("title", models.CharField(max_length=160)),
                ("kicker", models.CharField(default="Focus area", max_length=80)),
                ("summary", models.TextField()),
                (
                    "priority_kicker",
                    models.CharField(default="Program priority", max_length=120),
                ),
                (
                    "priority_title",
                    models.CharField(
                        default="Practical action built around community needs.",
                        max_length=180,
                    ),
                ),
                (
                    "points_text",
                    models.TextField(blank=True, help_text="One priority per line."),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FooterLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "group",
                    models.CharField(
                        choices=[
                            ("programs", "Programs"),
                            ("organization", "Organization"),
                            ("contact", "Contact"),
                        ],
                        max_length=32,
                    ),
                ),
                ("label", models.CharField(max_length=120)),
                ("url_name", models.CharField(blank=True, max_length=80)),
                ("external_url", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "ordering": ("sort_order", "id"),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="GalleryImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("image", models.FileField(blank=True, upload_to="cms/")),
                (
                    "static_image",
                    models.CharField(
                        blank=True,
                        help_text="Optional static image path, for example images/im-01.jpeg.",
                        max_length=255,
                    ),
                ),
                ("image_alt", models.CharField(blank=True, max_length=255)),
                ("gallery_key", models.SlugField(default="home_gallery")),
                ("caption", models.CharField(blank=True, max_length=120)),
                ("focus_class", models.CharField(blank=True, max_length=80)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="InternshipTrack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("role", models.CharField(max_length=140)),
                ("focus", models.TextField()),
                ("icon", models.CharField(default="IN", max_length=12)),
            ],
            options={
                "ordering": ("sort_order", "id"),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="NavigationItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("label", models.CharField(max_length=80)),
                ("url_name", models.CharField(blank=True, max_length=80)),
                ("external_url", models.CharField(blank=True, max_length=255)),
                ("is_cta", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ("sort_order", "id"),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="NewsItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("image", models.FileField(blank=True, upload_to="cms/")),
                (
                    "static_image",
                    models.CharField(
                        blank=True,
                        help_text="Optional static image path, for example images/im-01.jpeg.",
                        max_length=255,
                    ),
                ),
                ("image_alt", models.CharField(blank=True, max_length=255)),
                ("title", models.CharField(max_length=180)),
                ("date_label", models.CharField(blank=True, max_length=80)),
                ("summary", models.TextField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PageContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.FileField(blank=True, upload_to="cms/")),
                (
                    "static_image",
                    models.CharField(
                        blank=True,
                        help_text="Optional static image path, for example images/im-01.jpeg.",
                        max_length=255,
                    ),
                ),
                ("image_alt", models.CharField(blank=True, max_length=255)),
                ("slug", models.SlugField(unique=True)),
                ("title", models.CharField(max_length=160)),
                ("meta_title", models.CharField(blank=True, max_length=180)),
                ("hero_class", models.CharField(blank=True, max_length=80)),
                ("hero_kicker", models.CharField(blank=True, max_length=120)),
                ("hero_title", models.CharField(max_length=220)),
                ("hero_text", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Page content",
                "verbose_name_plural": "Page content",
                "ordering": ("slug",),
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("image", models.FileField(blank=True, upload_to="cms/")),
                (
                    "static_image",
                    models.CharField(
                        blank=True,
                        help_text="Optional static image path, for example images/im-01.jpeg.",
                        max_length=255,
                    ),
                ),
                ("image_alt", models.CharField(blank=True, max_length=255)),
                ("title", models.CharField(max_length=160)),
                ("description", models.TextField()),
                ("status", models.CharField(blank=True, max_length=80)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "singleton_key",
                    models.CharField(
                        default="main", editable=False, max_length=32, unique=True
                    ),
                ),
                (
                    "organization_name",
                    models.CharField(
                        default="Health Planet Foundation", max_length=160
                    ),
                ),
                (
                    "tagline",
                    models.CharField(
                        blank=True,
                        default="Sustainable environment, Healthy communities, Future generations",
                        max_length=220,
                    ),
                ),
                ("footer_about", models.TextField(blank=True)),
                (
                    "focus_dropdown_label",
                    models.CharField(default="Focus Areas", max_length=80),
                ),
                ("logo", models.FileField(blank=True, upload_to="branding/")),
                (
                    "static_logo",
                    models.CharField(
                        blank=True, default="images/HPF-logo.jpeg", max_length=255
                    ),
                ),
                ("contact_name", models.CharField(blank=True, max_length=160)),
                ("location", models.CharField(blank=True, max_length=160)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=40)),
                ("copyright_text", models.CharField(blank=True, max_length=180)),
            ],
            options={
                "verbose_name": "Site settings",
                "verbose_name_plural": "Site settings",
            },
        ),
        migrations.CreateModel(
            name="StatItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("label", models.CharField(max_length=80)),
                ("value", models.CharField(max_length=40)),
                ("description", models.CharField(max_length=160)),
            ],
            options={
                "ordering": ("sort_order", "id"),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "team",
                    models.CharField(
                        choices=[
                            ("management", "Management Team"),
                            ("board", "Board of Directors"),
                        ],
                        max_length=24,
                    ),
                ),
                ("name", models.CharField(max_length=140)),
                ("role", models.CharField(max_length=140)),
                ("bio", models.TextField()),
                ("initials", models.CharField(blank=True, max_length=8)),
                ("photo", models.FileField(blank=True, upload_to="staff/")),
                ("static_photo", models.CharField(blank=True, max_length=255)),
                ("photo_alt", models.CharField(blank=True, max_length=180)),
                ("photo_pending", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ("sort_order", "id"),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SectionContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.FileField(blank=True, upload_to="cms/")),
                (
                    "static_image",
                    models.CharField(
                        blank=True,
                        help_text="Optional static image path, for example images/im-01.jpeg.",
                        max_length=255,
                    ),
                ),
                ("image_alt", models.CharField(blank=True, max_length=255)),
                ("button_label", models.CharField(blank=True, max_length=120)),
                (
                    "button_url_name",
                    models.CharField(
                        blank=True,
                        help_text="Named Django route, for example projects, contact, donate.",
                        max_length=80,
                    ),
                ),
                (
                    "button_external_url",
                    models.CharField(
                        blank=True,
                        help_text="Full URL or mailto/tel link. Used when route name is blank.",
                        max_length=255,
                    ),
                ),
                ("page_slug", models.SlugField()),
                (
                    "key",
                    models.SlugField(
                        help_text="Template key, for example home_features or about_team."
                    ),
                ),
                ("kicker", models.CharField(blank=True, max_length=120)),
                ("title", models.CharField(blank=True, max_length=220)),
                ("body", models.TextField(blank=True)),
                ("image_caption", models.CharField(blank=True, max_length=160)),
            ],
            options={
                "ordering": ("page_slug", "key"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("page_slug", "key"), name="unique_section_per_page"
                    )
                ],
            },
        ),
    ]
