# Generated by Django 6.0.1 on 2026-05-12 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_home_partners'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerLogo',
            fields=[
            ],
            options={
                'verbose_name': 'Home partner logo',
                'verbose_name_plural': 'Home partner logos',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.galleryimage',),
        ),
    ]
