# Generated by Django 6.0.1 on 2026-05-15 09:23

import django.db.models.deletion
from django.db import migrations, models
from django.utils.text import slugify


NEWS_DETAILS = {
    "RANA Bootcamp advances epidemic preparedness across Africa": {
        "slug": "rana-bootcamp-advances-epidemic-preparedness-across-africa",
        "body": "The Resilience Action Network Africa (RANA), in partnership with Resolve to Save Lives, convened civil society and community organizations from 11 African countries for a focused bootcamp on epidemic preparedness and community-engaged disease surveillance.\n\nHeld at The Tribe Hotel in Nairobi, Kenya from 28 to 30 April 2026, the bootcamp created space for organizations to align on a shared agenda for stronger disease surveillance ecosystems across Africa.\n\nThe discussions took place alongside the World Health Summit Regional Meeting and contributed to the Declaration for an Enabling Disease Surveillance Ecosystem, emphasizing collaboration, readiness, and community trust.\n\nHealth Planet Foundation Zambia was represented by Executive Director Doreen McGeachy, who contributed to the continental dialogue on practical approaches for preparedness and response.",
        "gallery_images": [
            (
                "images/news/rana-bootcamp-2026.jpg",
                "Plenary session at the RANA Bootcamp in Nairobi",
                "RANA Bootcamp plenary session",
                10,
            ),
            (
                "images/news/rana-bootcamp-2026-group.jpg",
                "Participants at the RANA Bootcamp in Nairobi",
                "Regional partners gathered in Nairobi",
                20,
            ),
        ],
    },
    "HFPZ joins continental dialogue on demographic dividend and reproductive health": {
        "slug": "hpfz-joins-continental-dialogue-on-demographic-dividend-and-reproductive-health",
        "body": "The 1st Continental Conference for Non-State Actors on the Demographic Dividend and Reproductive Health was held from 8 to 10 April 2026 at the Intercontinental Hotel in Lusaka, Zambia.\n\nThe conference brought together more than 200 delegates from across Africa, including civil society organizations, academia, private sector leaders, and youth advocates.\n\nConvening partners included AUDA-NEPAD, Med Rap Zambia, UNAIDS, and the University of Zambia. The key outcome was the Lusaka 2026 Call for Action, which strengthened the role of non-state actors in advancing demographic dividend and reproductive health priorities.\n\nHealth Planet Foundation Zambia was represented by Programs Manager Nolia Chipundo. The event closed with a 5km solidarity walk from Pamodzi Hotel to the University of Zambia.",
        "gallery_images": [
            (
                "images/news/continental-conference-lusaka-2026.jpg",
                "Delegates at the continental conference plenary session in Lusaka",
                "Conference plenary session",
                10,
            ),
            (
                "images/news/continental-conference-lusaka-2026-panel.jpg",
                "Panel discussion at the continental conference in Lusaka",
                "Panel dialogue",
                20,
            ),
            (
                "images/news/continental-conference-lusaka-2026-delegates.jpg",
                "Delegates participating in the continental conference",
                "Delegates in session",
                30,
            ),
            (
                "images/news/continental-conference-lusaka-2026-walk.jpg",
                "Solidarity walk during the continental conference",
                "Solidarity walk",
                40,
            ),
        ],
    },
}


def article_slug(title, used_slugs):
    base_slug = slugify(title)[:180] or "news"
    slug = base_slug
    counter = 2
    while slug in used_slugs:
        slug = f"{base_slug}-{counter}"
        counter += 1
    used_slugs.add(slug)
    return slug


def seed_news_articles(apps, schema_editor):
    NewsItem = apps.get_model("core", "NewsItem")
    NewsImage = apps.get_model("core", "NewsImage")
    used_slugs = set()

    for news_item in NewsItem.objects.order_by("sort_order", "id"):
        details = NEWS_DETAILS.get(news_item.title, {})
        news_item.slug = details.get("slug") or article_slug(news_item.title, used_slugs)
        used_slugs.add(news_item.slug)
        if not news_item.body:
            news_item.body = details.get("body") or news_item.summary
        news_item.save(update_fields=["slug", "body"])

        gallery_images = details.get("gallery_images")
        if gallery_images is None and news_item.static_image:
            gallery_images = [
                (
                    news_item.static_image,
                    news_item.image_alt,
                    news_item.title,
                    10,
                )
            ]

        for static_image, image_alt, caption, sort_order in gallery_images or []:
            NewsImage.objects.update_or_create(
                news_item=news_item,
                static_image=static_image,
                defaults={
                    "image_alt": image_alt,
                    "caption": caption,
                    "sort_order": sort_order,
                    "is_active": True,
                },
            )


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_newsitem_event_date_newsitem_participants_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsitem",
            name="body",
            field=models.TextField(
                blank=True,
                help_text="Optional long-form article content. Use blank lines to separate paragraphs.",
            ),
        ),
        migrations.AddField(
            model_name="newsitem",
            name="slug",
            # Avoid creating PostgreSQL's temporary LIKE index before this
            # populated field becomes unique later in this migration.
            field=models.SlugField(blank=True, db_index=False, max_length=220),
        ),
        migrations.CreateModel(
            name="NewsImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("image", models.FileField(blank=True, upload_to="cms/")),
                (
                    "static_image",
                    models.CharField(
                        blank=True,
                        help_text="Optional static image path, for example images/im-01.jpeg.",
                        max_length=255,
                    ),
                ),
                ("image_alt", models.CharField(blank=True, max_length=255)),
                ("caption", models.CharField(blank=True, max_length=180)),
                (
                    "news_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery_images",
                        to="core.newsitem",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RunPython(seed_news_articles, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="newsitem",
            name="slug",
            field=models.SlugField(blank=True, max_length=220, unique=True),
        ),
    ]
