# Generated by Django 6.0.1 on 2026-05-26 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_add_privacy_and_form_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="pagecontent",
            name="meta_description",
            field=models.CharField(
                blank=True,
                help_text="Short search and sharing description. Leave blank to use the hero summary.",
                max_length=280,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="body",
            field=models.TextField(
                blank=True,
                help_text="Long-form impact story. Use blank lines to separate paragraphs.",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="location",
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name="project",
            name="outcomes_text",
            field=models.TextField(
                blank=True, help_text="One measurable result or outcome per line."
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="period_label",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="project",
            name="slug",
            field=models.SlugField(blank=True, max_length=220, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="analytics_measurement_id",
            field=models.CharField(
                blank=True,
                help_text="Optional Google Analytics 4 Measurement ID, for example G-XXXXXXXXXX.",
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="ProjectImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("image", models.FileField(blank=True, upload_to="cms/")),
                (
                    "static_image",
                    models.CharField(
                        blank=True,
                        help_text="Optional static image path, for example images/im-01.jpeg.",
                        max_length=255,
                    ),
                ),
                ("image_alt", models.CharField(blank=True, max_length=255)),
                ("caption", models.CharField(blank=True, max_length=180)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery_images",
                        to="core.project",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
